baseURL: https://metaveeluangthawornkul.netlify.app/
languageCode: en-us
title: Porfolio Website for Metavee Luangthawornkul
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: More about me
    subtitle: |-
      Hello! WELCOME TO MY PERSONAL BLOG.
    title: Hi, my name is Metavee Luangthawornkul
  blog: {}
  contact:
    address:
      - city: London
        country: United Kingdom
        street: Brown Street
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: m.metavee@gmail.com
        title: Email
    enable: yes
    phone:
      - phone: (+44) 7554-701599
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Company Name
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
    #  - icon: fa-twitter
     #   label: Twitter
      #  url: https://www.twitter.com
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com/metaveel
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/jennyjnx/
      - icon: fa-github
        label: GitHub
        url: https://github.com/metaveel
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/metaveel/
  image: ''
  name: Your name
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      - name: Generic Blog
        url: blogs/ipsum
      - name: Elements
        url: elements.html
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: about_me.jpg
        subtitle: Hello ! I'm Jenny 
        title: About me
        url: blogs/metavee
      - image: pic02.jpg
        subtitle: Risk Return of DJIA Stocks
        title: Dow Jones Industrial Average
        url: blogs/risk_return
      - image: pic12.jpg
        subtitle: Making graph with ggplot
        title: My first R assigment 
        url: blogs/assignment_one
      - image: pic04.jpg
        subtitle: xxx
        title: My Second R assigment
        url: blogs/ipsum
      - image: pic11.jpg
        subtitle: My greatest achievement 
        title: A Private Equity Analyst in Bangkok 
        url: blogs/private_equity
      - image: dog.jpg
        subtitle: EATING WELL IS A FORM OF SELF RESPECT
        title: Food Matters!
        url: blogs/ipsum
  two:
    buttonText: Get Started
    enable: yes
    subtitle: "A beautiful day begins with a beautiful mindset"
    title: This is all about myself 
    image: sunrise.jpg
    url: blogs
