---
categories:  
- ""    #the front matter should be like the one found in, e.g., blog2.md. It cannot be like the normal Rmd we used
- ""
date: "2021-10-17"
description: My R assignment 2 
draft: false
image: spices.jpeg # save picture in \static\img\blogs. Acceptable formats= jpg, jpeg, or png . Your iPhone pics wont work

keywords: ""
slug: assignment_two 
title: My R assignment 2
---

<script src="/rmarkdown-libs/header-attrs/header-attrs.js"></script>


<div id="my-second-r-assigment" class="section level1">
<h1>My Second R Assigment</h1>
<p>The following graphs are included in my second R assignment I had done with my study group.
1) Alcohol consumption by countries : Beer, Wine, and Spirit
2) Biden’s Approval Margins
3) Transport for London bike sharing
4) Chang in the US CPI and its components over the period</p>
</div>
<div id="climate-change-and-temperature-anomalies" class="section level1">
<h1>Climate change and temperature anomalies</h1>
<div id="getting-the-data-in-the-right-format" class="section level2">
<h2>Getting the data in the right format</h2>
<p>Loading Combined Land-Surface Air and Sea-Surface Water Temperature Anomalies in the Northern Hemisphere from <a href="https://data.giss.nasa.gov/gistemp">NASA’s Goddard Institute for Space Studies</a></p>
<pre class="r"><code>weather &lt;- 
  read_csv(&quot;https://data.giss.nasa.gov/gistemp/tabledata_v4/NH.Ts+dSST.csv&quot;, 
           skip = 1, 
           na = &quot;***&quot;) #loading the weather data set, skipping the first row and defining the encoding for missing variables </code></pre>
<p>Creating a long-format dataframe ‘tidyweather’ with the year and month variables from ‘weather’</p>
<pre class="r"><code>tidyweather&lt;-weather %&gt;%
  select(Year:Dec) %&gt;% #selecting the year and the months to make a long table
  pivot_longer(cols = 2:13, #using the the columns 2 to 13 to make a long table
               names_to = &quot;Month&quot;,
               values_to = &quot;delta&quot;) </code></pre>
<p>The ‘tidyweather’ dataframe has three variables: year, month, and delta which represents temperature deviation</p>
</div>
<div id="time-series-scatter-plot" class="section level2">
<h2>Time-series scatter plot</h2>
<p>We use the mutate function to create a ‘date’ variable to plot the data chronologically. Then we create a time-series scatter plot with a trendline.</p>
<pre class="r"><code>tidyweather &lt;- tidyweather %&gt;%
  mutate(date = ymd(paste(as.character(Year), Month, &quot;1&quot;)), #using the mutate to create a new variable and to split the date between years and month 
         month = month(date),label=TRUE,
         year = year(date))

ggplot(tidyweather, aes(x=date, y = delta))+
  geom_point()+ #plotting the deltas for each month over time
  geom_smooth(color=&quot;red&quot;) + #adding a red trendline
  theme_bw() +
  labs (
    title = &quot;Weather Anomalies&quot;)</code></pre>
<p><img src="/blogs/assignment_two_files/figure-html/scatter_plot-1.png" width="648" style="display: block; margin: auto;" /></p>
<p>The scatterplot show that temperature anomalies has been has been steadily increasing from the 1950-1980s base period, particularly in after the 1970s. The overall data shows that the temperature anomalies represent higher temperature after the 1950s and lower before 1950s.</p>
</div>
<div id="time-series-scatter-plot-grouped-by-month" class="section level2">
<h2>Time-series scatter plot grouped by month</h2>
<p>In the next chart, we are using <code>facet_wrap()</code> to investigate whether the effect of increasing temperature is more pronounced in particular months.</p>
<pre class="r"><code>ggplot(tidyweather,aes(x=date,y=delta))+
  geom_point()+
  facet_wrap(~fct_reorder(Month, date))+ #faceting the deltas for each month and order each month in chronological order
  geom_smooth(color=&quot;red&quot;) + #adding a line that averages the datapoints and colour it in red
  theme_bw() + #setting a more readable theme
  labs(title=&quot;Weather Anomalies Per Month&quot;)</code></pre>
<p><img src="/blogs/assignment_two_files/figure-html/facet_wrap-1.png" width="648" style="display: block; margin: auto;" /></p>
<p>By grouping the ‘tidyweather’ data by month and creating a scatter plot with trend lines, we see that all months show increasing temperature deviations. An interesting observation is that the temperature deviations are closer to each other for certain months and show a higher year on year variability for other months. December to February shows a high variability from year to year whereas the year on year variations for May to September show less variability. In more recent years, we also see that the months December to February show the highest anomalies.</p>
</div>
<div id="density-plot-grouped-by-time-periods" class="section level2">
<h2>Density plot grouped by time-periods</h2>
<p>we create a new data frame ‘comparison’ where we group the data into five different time periods: 1881-1920, 1921-1950, 1951-1980, 1981-2010 and 2011-present.</p>
<pre class="r"><code>comparison &lt;- tidyweather %&gt;% 
  filter(Year&gt;= 1881) %&gt;% #remove years prior to 1881
  #create new variable &#39;interval&#39;, and assign values based on criteria below:
  mutate(interval = case_when(
    Year %in% c(1881:1920) ~ &quot;1881-1920&quot;,
    Year %in% c(1921:1950) ~ &quot;1921-1950&quot;,
    Year %in% c(1951:1980) ~ &quot;1951-1980&quot;,
    Year %in% c(1981:2010) ~ &quot;1981-2010&quot;,
  TRUE ~ &quot;2011-present&quot;))</code></pre>
<p>We are creating a density plot to study the distribution of monthly deviations</p>
<pre class="r"><code>ggplot(comparison, aes(x=delta, fill=interval))+ #using fill to color the intervals
  geom_density(alpha=0.2) +   #density plot with tranparency set to 20%
  theme_bw() +                #theme
  labs (
    title = &quot;Density Plot for Monthly Temperature Anomalies&quot;,
    y     = &quot;Density&quot;) #changing y-axis label to sentence case</code></pre>
<p><img src="/blogs/assignment_two_files/figure-html/density_plot-1.png" width="648" style="display: block; margin: auto;" /></p>
<p>The density plot shows us that the temperature deviations have been higher in more recent years, indicated by the ‘1981-2010’ and ‘2011-present’ distributions having higher median’s and the majority of observations being higher than the other intervals. The density plot also shows us that the temperature deviations are more spread out in the more recent distributions, indicating higher temperature variability compared to the base and older years.</p>
</div>
<div id="scatter-plot-of-average-annual-anomalies" class="section level2">
<h2>Scatter plot of average annual anomalies</h2>
<p>We are creating a scatter plot with a trendline to show average annual anomalies</p>
<pre class="r"><code>#creating yearly averages
average_annual_anomaly &lt;- tidyweather %&gt;% 
  group_by(Year) %&gt;%   #grouping data by Year
  # creating summaries for mean delta 
  # use `na.rm=TRUE` to eliminate NA (not available) values 
  summarise(annual_average_delta=mean(delta,na.rm=TRUE))

#plotting the data:
ggplot(average_annual_anomaly, aes(x=Year, y= annual_average_delta))+
  geom_point()+
  #Fit the best fit line, using LOESS method
  geom_smooth() +
  #change to theme_bw() to have white background + black frame around plot
  theme_bw() +
  labs (
    title = &quot;Average Yearly Anomaly&quot;,
    y     = &quot;Average Annual Delta&quot;)                         </code></pre>
<p><img src="/blogs/assignment_two_files/figure-html/averaging-1.png" width="648" style="display: block; margin: auto;" /></p>
<p>The scatter plot of average annual temperature anomalies reaffirms our observations about an increase in temperature in more recent time compared to the base between ‘1951-1980’.</p>
</div>
<div id="confidence-interval-for-delta" class="section level2">
<h2>Confidence Interval for <code>delta</code></h2>
<p>We are constructing a confidence interval for the average annual delta between ‘2011-present’ in two ways. Using a formula and using a bootstrap simulation with the <code>infer</code> package.</p>
<p>First we will construct the confidence interval using a formula:</p>
<pre class="r"><code>formula_ci &lt;- comparison %&gt;% 
  na.omit()%&gt;%
  filter(interval==&quot;2011-present&quot;) %&gt;% #chossing the interval 2011-present with the filter function
  summarise(mean_delta=mean(delta), #using the summarise function to compute the statistics we need (mean, SD, count, SE, lower/upper 95% CI)
            sd_delta=sd(delta),
            count=n(),
            se_delta=sd(delta)/sqrt(count),
            t_critical=qt(0.975,count-1),
            margin_of_error=t_critical*se_delta,
            lower_ci_95=mean_delta-t_critical*se_delta,
            higher_ci_95=mean_delta+t_critical*se_delta) #calculating summary statistics for temperature deviation (delta) 
formula_ci #displaying the formula</code></pre>
<pre><code>## # A tibble: 1 x 8
##   mean_delta sd_delta count se_delta t_critical margin_of_error lower_ci_95
##        &lt;dbl&gt;    &lt;dbl&gt; &lt;int&gt;    &lt;dbl&gt;      &lt;dbl&gt;           &lt;dbl&gt;       &lt;dbl&gt;
## 1       1.06    0.274   129   0.0241       1.98          0.0478        1.01
## # ... with 1 more variable: higher_ci_95 &lt;dbl&gt;</code></pre>
<p>Our confidence interval calculated using the formula is saved to ‘formula_ci’. The lower 5th percentile mark is 1.01 degrees, the higher 95th percentile is 1.11 and our mean temperature anomaly is 1.06.</p>
<p>Then we also try to construct the same confidence interval using the bootstrap method.</p>
<pre class="r"><code>set.seed(1) #setting a seed to ensure consistency

bootstrap_ci &lt;- comparison %&gt;%  
  filter(interval==&quot;2011-present&quot;)%&gt;% #filtering to choose the interval 2011-present
  specify(response=delta) %&gt;% #using the specify function for the point estimate delta
  generate(reps=1000,type=&quot;bootstrap&quot;)%&gt;% #running the formula 1,000 times
  calculate(stat=&quot;mean&quot;) %&gt;% #calculating the mean
  get_confidence_interval(level=0.95, type= &quot;percentile&quot;)

bootstrap_ci #showing bootstrap_CI</code></pre>
<pre><code>## # A tibble: 1 x 2
##   lower_ci upper_ci
##      &lt;dbl&gt;    &lt;dbl&gt;
## 1     1.01     1.11</code></pre>
<p>Our confidence interval from the bootstrap method is saved to ‘bootstrap_ci’. We have the same lower and upper confidence interval at 1.01 and 1.11 respectively.</p>
</div>
<div id="conclusion" class="section level2">
<h2>Conclusion</h2>
<p>The data shows us that the temperature anomalies are higher and more distributed in later years compared to the base between 1950-1980 and years before the base, pre-1950s. It also showed us that the temperature anomaly distribution is more spread out in the months December to February. According to <a href="https://earthobservatory.nasa.gov/world-of-change/decadaltemp.php">NASA</a></p>
<blockquote>
<p>A one-degree global change is significant because it takes a vast amount of heat to warm all the oceans, atmosphere, and land by that much. In the past, a one- to two-degree drop was all it took to plunge the Earth into the Little Ice Age.</p>
</blockquote>
<p>Our 95% confidence interval indicates that the mean of temperature anomalies is likely to be above 1 degree. This is scary because it means global warming is happening and that the shift in temperatures is significant. The data shows that the current average deviation from the mean temperature is 1.01 degree increase in our lower confidence interval and 1.11 in the higher.</p>
</div>
</div>
<div id="bidens-approval-margins" class="section level1">
<h1>Biden’s Approval Margins</h1>
<div id="downloading-and-cleaning-data" class="section level2">
<h2>Downloading and cleaning data</h2>
<p>The date variables are given as characters and need to be formatted as dates</p>
<pre class="r"><code># Import approval polls data directly off fivethirtyeight website
approval_polllist &lt;- read_csv(&#39;https://projects.fivethirtyeight.com/biden-approval-data/approval_polllist.csv&#39;) 

glimpse(approval_polllist) #taking a look at the data</code></pre>
<pre><code>## Rows: 1,918
## Columns: 22
## $ president           &lt;chr&gt; &quot;Joseph R. Biden Jr.&quot;, &quot;Joseph R. Biden Jr.&quot;, &quot;Jos~
## $ subgroup            &lt;chr&gt; &quot;All polls&quot;, &quot;All polls&quot;, &quot;All polls&quot;, &quot;All polls&quot;~
## $ modeldate           &lt;chr&gt; &quot;10/15/2021&quot;, &quot;10/15/2021&quot;, &quot;10/15/2021&quot;, &quot;10/15/2~
## $ startdate           &lt;chr&gt; &quot;1/19/2021&quot;, &quot;1/19/2021&quot;, &quot;1/20/2021&quot;, &quot;1/20/2021&quot;~
## $ enddate             &lt;chr&gt; &quot;1/21/2021&quot;, &quot;1/21/2021&quot;, &quot;1/21/2021&quot;, &quot;1/22/2021&quot;~
## $ pollster            &lt;chr&gt; &quot;Morning Consult&quot;, &quot;Rasmussen Reports/Pulse Opinio~
## $ grade               &lt;chr&gt; &quot;B&quot;, &quot;B&quot;, &quot;B+&quot;, &quot;B&quot;, &quot;B-&quot;, &quot;B&quot;, &quot;B&quot;, &quot;B&quot;, &quot;B-&quot;, &quot;B~
## $ samplesize          &lt;dbl&gt; 15000, 1500, 1516, 15000, 1115, 1993, 15000, 1500,~
## $ population          &lt;chr&gt; &quot;a&quot;, &quot;lv&quot;, &quot;a&quot;, &quot;a&quot;, &quot;a&quot;, &quot;rv&quot;, &quot;a&quot;, &quot;lv&quot;, &quot;rv&quot;, &quot;~
## $ weight              &lt;dbl&gt; 0.2594, 0.3382, 1.2454, 0.2333, 1.1014, 0.0930, 0.~
## $ influence           &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,~
## $ approve             &lt;dbl&gt; 50, 48, 45, 51, 55, 56, 52, 48, 58, 63, 54, 55, 48~
## $ disapprove          &lt;dbl&gt; 28, 45, 28, 28, 32, 31, 29, 47, 32, 37, 30, 33, 47~
## $ adjusted_approve    &lt;dbl&gt; 48.6, 50.5, 46.5, 49.6, 53.9, 54.6, 50.6, 50.5, 57~
## $ adjusted_disapprove &lt;dbl&gt; 31.2, 38.8, 28.4, 31.2, 33.0, 34.2, 32.2, 40.8, 33~
## $ multiversions       &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA~
## $ tracking            &lt;lgl&gt; TRUE, TRUE, NA, TRUE, NA, NA, TRUE, TRUE, NA, NA, ~
## $ url                 &lt;chr&gt; &quot;https://morningconsult.com/form/global-leader-app~
## $ poll_id             &lt;dbl&gt; 74272, 74247, 74327, 74273, 74248, 74246, 74274, 7~
## $ question_id         &lt;dbl&gt; 139491, 139395, 139570, 139492, 139404, 139394, 13~
## $ createddate         &lt;chr&gt; &quot;1/28/2021&quot;, &quot;1/22/2021&quot;, &quot;2/2/2021&quot;, &quot;1/28/2021&quot;,~
## $ timestamp           &lt;chr&gt; &quot;13:12:11 15 Oct 2021&quot;, &quot;13:12:11 15 Oct 2021&quot;, &quot;1~</code></pre>
<pre class="r"><code>#using `lubridate` to fix dates, as they are given as characters.
approval_polllist$modeldate&lt;-mdy(approval_polllist$modeldate)
approval_polllist$startdate&lt;-mdy(approval_polllist$startdate)
approval_polllist$enddate&lt;-mdy(approval_polllist$enddate)
approval_polllist$createddate &lt;-mdy(approval_polllist$createddate )
approval_polllist$timestamp   &lt;-as_datetime(approval_polllist$createddate )
glimpse(approval_polllist) #checking that it was fixed</code></pre>
<pre><code>## Rows: 1,918
## Columns: 22
## $ president           &lt;chr&gt; &quot;Joseph R. Biden Jr.&quot;, &quot;Joseph R. Biden Jr.&quot;, &quot;Jos~
## $ subgroup            &lt;chr&gt; &quot;All polls&quot;, &quot;All polls&quot;, &quot;All polls&quot;, &quot;All polls&quot;~
## $ modeldate           &lt;date&gt; 2021-10-15, 2021-10-15, 2021-10-15, 2021-10-15, 2~
## $ startdate           &lt;date&gt; 2021-01-19, 2021-01-19, 2021-01-20, 2021-01-20, 2~
## $ enddate             &lt;date&gt; 2021-01-21, 2021-01-21, 2021-01-21, 2021-01-22, 2~
## $ pollster            &lt;chr&gt; &quot;Morning Consult&quot;, &quot;Rasmussen Reports/Pulse Opinio~
## $ grade               &lt;chr&gt; &quot;B&quot;, &quot;B&quot;, &quot;B+&quot;, &quot;B&quot;, &quot;B-&quot;, &quot;B&quot;, &quot;B&quot;, &quot;B&quot;, &quot;B-&quot;, &quot;B~
## $ samplesize          &lt;dbl&gt; 15000, 1500, 1516, 15000, 1115, 1993, 15000, 1500,~
## $ population          &lt;chr&gt; &quot;a&quot;, &quot;lv&quot;, &quot;a&quot;, &quot;a&quot;, &quot;a&quot;, &quot;rv&quot;, &quot;a&quot;, &quot;lv&quot;, &quot;rv&quot;, &quot;~
## $ weight              &lt;dbl&gt; 0.2594, 0.3382, 1.2454, 0.2333, 1.1014, 0.0930, 0.~
## $ influence           &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,~
## $ approve             &lt;dbl&gt; 50, 48, 45, 51, 55, 56, 52, 48, 58, 63, 54, 55, 48~
## $ disapprove          &lt;dbl&gt; 28, 45, 28, 28, 32, 31, 29, 47, 32, 37, 30, 33, 47~
## $ adjusted_approve    &lt;dbl&gt; 48.6, 50.5, 46.5, 49.6, 53.9, 54.6, 50.6, 50.5, 57~
## $ adjusted_disapprove &lt;dbl&gt; 31.2, 38.8, 28.4, 31.2, 33.0, 34.2, 32.2, 40.8, 33~
## $ multiversions       &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA~
## $ tracking            &lt;lgl&gt; TRUE, TRUE, NA, TRUE, NA, NA, TRUE, TRUE, NA, NA, ~
## $ url                 &lt;chr&gt; &quot;https://morningconsult.com/form/global-leader-app~
## $ poll_id             &lt;dbl&gt; 74272, 74247, 74327, 74273, 74248, 74246, 74274, 7~
## $ question_id         &lt;dbl&gt; 139491, 139395, 139570, 139492, 139404, 139394, 13~
## $ createddate         &lt;date&gt; 2021-01-28, 2021-01-22, 2021-02-02, 2021-01-28, 2~
## $ timestamp           &lt;dttm&gt; 2021-01-28, 2021-01-22, 2021-02-02, 2021-01-28, 2~</code></pre>
</div>
<div id="create-a-plot" class="section level2">
<h2>Create a plot</h2>
<p>We are creating a plot showing Joe Biden’s net approval margin over time alond with its 95% confidence interval.</p>
<pre class="r"><code>approval_polllist_ci&lt;-approval_polllist %&gt;%
  mutate(week_of_the_year=week(enddate),net_approval_rate=approve-disapprove)%&gt;% #calculating the net approval rating
  filter(subgroup==&quot;All polls&quot;) %&gt;% #filtering for all polls
  group_by(week_of_the_year)%&gt;% #grouping by week
  summarize(average_net_approval_rate=mean(net_approval_rate),
            sd_net_approval_rate=sd(net_approval_rate),
            count=n(),
            se_net_approval_rate=sd_net_approval_rate/sqrt(count),
            t_critical=qt(0.975,count-1),
             margin_of_error=t_critical*se_net_approval_rate,
            lower_ci_95=average_net_approval_rate-t_critical*se_net_approval_rate,
            higher_ci_95=average_net_approval_rate+t_critical*se_net_approval_rate,
            na.rm=TRUE) %&gt;% #calculating the confidence intervals for each week
  ggplot(aes(x=week_of_the_year,y=average_net_approval_rate))+ #building the plot
  geom_point(colour=&quot;red3&quot;,size=0.2,xlim=40)+ #plotting each data point
  geom_line(colour=&quot;red3&quot;,size=0.1)+ #adding a line that links the data points
  theme_bw()+
  geom_smooth(se=FALSE,legend.position=NA,colour=&quot;blue&quot;,size=0.4)+ #adding a trendline
  geom_ribbon(aes(ymin=lower_ci_95,ymax=higher_ci_95),colour=&quot;red3&quot;,alpha=0.1,linetype=&quot;dashed&quot;,size=0.1)+ #colouring the CI
  geom_hline(aes(yintercept=0),size=0.8,colour=&quot;orange&quot;)+ #adding a horizontal line on the y=0 axis
  theme(legend.position = &quot;none&quot;, #setting a more easily readable theme
        legend.background=element_blank(),
        plot.title=element_text(size=10,face=&quot;bold&quot;),
        axis.ticks=element_blank(),
        axis.text=element_text(size=5),
        strip.text=element_text(size=6),
        axis.title=element_text(size=6,face=&quot;bold&quot;),
        plot.subtitle=element_text(size=8,face=&quot;bold&quot;),
        panel.border = element_blank(),
        aspect.ratio=1377/2500)+
  scale_y_continuous(expand = c(0, 1), breaks= seq(-15,10,by=2.5),limits=c(-15,40))+ #setting y-axis boundaries to make the data more readable
  scale_x_continuous(expand = c(0, 0),breaks= seq(0,40,by=13),limits=c(1,40))+ #setting x-axis boundaries to make the data more readable
    labs(title=&quot;Estimating Approval Margin (Approve - Disapprove) for Joe Biden&quot;, 
       subtitle=&quot;Weekly Average of All Polls&quot;,
       x=&quot;Week of the year&quot;, 
       y=&quot;Average Approval Margin (approve-disapprove)&quot;)+
  annotate(&quot;text&quot;,x=20,y=40,label=&quot;2021&quot;,size=2)

approval_polllist_ci #printing to view the plot</code></pre>
<p><img src="/blogs/assignment_two_files/figure-html/poll_plot-1.png" width="648" style="display: block; margin: auto;" /></p>
</div>
<div id="compare-confidence-intervals" class="section level2">
<h2>Compare Confidence Intervals</h2>
<p>The confidence intervals for <code>week 3</code> is very wide compared to the other weeks, whereas the confidence interval for <code>week 25</code> is narrower. The reason the confidence interval for week 3 is wide is because it is the first week we have data for and our data starts in the middle of the week. Week 3 in 2021 was from 18-24. January. The ‘enddate’ variable from the data set that we use to plot the weeks only starts from January 21st. Therefore, we believe the number of data points in week 3 to be much lower than in other weeks, leading to a wider confidence interval.</p>
</div>
</div>
<div id="challenge-1-excess-rentals-in-transport-for-london-bike-sharing" class="section level1">
<h1>Challenge 1: Excess rentals in Transport for London bike sharing</h1>
<div id="downloading-and-cleaning-data-1" class="section level2">
<h2>Downloading and cleaning data</h2>
<p>We download the latest TFL data and read it as a dataframe. Then we change the date variables to get year, month and week.</p>
<pre class="r"><code>url &lt;- &quot;https://data.london.gov.uk/download/number-bicycle-hires/ac29363e-e0cb-47cc-a97a-e216d900a6b0/tfl-daily-cycle-hires.xlsx&quot;

# Download TFL data to temporary file
httr::GET(url, write_disk(bike.temp &lt;- tempfile(fileext = &quot;.xlsx&quot;)))</code></pre>
<pre><code>## Response [https://airdrive-secure.s3-eu-west-1.amazonaws.com/london/dataset/number-bicycle-hires/2021-09-23T12%3A52%3A20/tfl-daily-cycle-hires.xlsx?X-Amz-Algorithm=AWS4-HMAC-SHA256&amp;X-Amz-Credential=AKIAJJDIMAIVZJDICKHA%2F20211018%2Feu-west-1%2Fs3%2Faws4_request&amp;X-Amz-Date=20211018T102500Z&amp;X-Amz-Expires=300&amp;X-Amz-Signature=5002b5714d797c2111e473894750869ba53ac7ab975e0c865661152d57314a4f&amp;X-Amz-SignedHeaders=host]
##   Date: 2021-10-18 10:26
##   Status: 200
##   Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
##   Size: 174 kB
## &lt;ON DISK&gt;  C:\Users\metav\AppData\Local\Temp\RtmpAnLWuH\file60745f241fde.xlsx</code></pre>
<pre class="r"><code># Use read_excel to read it as dataframe
bike0 &lt;- read_excel(bike.temp,
                   sheet = &quot;Data&quot;,
                   range = cell_cols(&quot;A:B&quot;))

# change dates to get year, month, and week
bike &lt;- bike0 %&gt;% 
  clean_names() %&gt;% 
  rename (bikes_hired = number_of_bicycle_hires) %&gt;% 
  mutate (year = year(day),
          month = lubridate::month(day, label = TRUE),
          week = isoweek(day))</code></pre>
<p><strong>Look at May and Jun and compare 2020 with the previous years. What’s happening?</strong></p>
<p>Looking at the facet grid chart with the number of bikes hired by month and year, we see a much smaller peak in May and June 2020 compared to previous years. What we see is that number of days with a high number of rentals, aprx. 30-50k is much less than previous years. The number of bikes rented each day is much more inconsistent and varies along the entire spectrum. This is a result of COVID lockdown, where bike usage patterns changed. We see that the rentals take up again in July, when lockdown was lifted, and the distribution starts to normalize.</p>
</div>
<div id="reproducing-graphs" class="section level2">
<h2>Reproducing graphs</h2>
<pre class="r"><code>data_bike &lt;-bike %&gt;%
  group_by(month,year) %&gt;% #grouping by month and year
  summarize(actual_rentals=mean(bikes_hired)) #selecting by the number of bikes hired to create the number of bikes hired by every month of each year

expected_bike &lt;-data_bike %&gt;%
  group_by(month) %&gt;% #grouping by month
  filter(year %in% c(2016,2017,2018,2019)) %&gt;% #filtering the months we want to analyse
  summarize(expected_rentals=mean(actual_rentals)) #selecting by the number of bikes hired to create the number of bikes hired by every month overall no matter the year

df3 &lt;- left_join(data_bike, expected_bike, by = c(&quot;month&quot;)) %&gt;% 
  filter(year %in% c(2016,2017,2018,2019,2020,2021)) %&gt;% #filtering the months we want to analyse
  mutate(excess_rentals = actual_rentals - expected_rentals, #using the mutate function to obtain the excess rentals
         up = ifelse(actual_rentals&gt;expected_rentals, actual_rentals, expected_rentals), #using the mutate function to obtain the excess rentals
         down = ifelse(actual_rentals&lt;expected_rentals, actual_rentals, expected_rentals)) #using the mutate function to obtain the deficit rentals

ggplot(df3,aes(x=month,y=actual_rentals,group=1))+
  geom_line(colour=&quot;black&quot;,size=0.2)+ #plotting the rentals observed by month
  geom_line(aes(x=month,y=expected_rentals,group=1),colour=&quot;blue&quot;,size=1)+ #plotting the expected rentals by month
  geom_ribbon(aes(ymin=actual_rentals,ymax=up),fill=&quot;#CB454A&quot;,alpha=0.4)+ #filling in green the excess of bike rentals
  geom_ribbon(aes(ymin=down,ymax=actual_rentals),fill=&quot;#7DCD85&quot;,alpha=0.4)  + #filling in red the deficit of bike rentals
  facet_wrap(~year)+ #faceting by year
  theme_bw()+
  labs(title=&quot;Monthly changes in Tfl bike rentals&quot;,
       subtitle = &quot;Change from monthly average shown in blue
and calculated between 2016-2019&quot;,
         y=&quot;Bike rentals&quot;,x=&quot;&quot;,caption=&quot;Source:Tfl, London Data Store&quot;)+
  theme(legend.position = &quot;none&quot;, #setting a theme to make the graph more easily readable
        legend.background=element_blank(),
        plot.title=element_text(size=6,face=&quot;bold&quot;),
        axis.ticks=element_blank(),
        axis.text=element_text(size=4),
        strip.text=element_text(size=4),
        axis.title=element_text(size=4,face=&quot;bold&quot;),
        plot.subtitle=element_text(size=4),
        plot.caption = element_text(size=4),
        panel.border = element_rect(colour=&quot;white&quot;),
        strip.background = element_rect(color=&quot;transparent&quot;,fill=&quot;transparent&quot;))</code></pre>
<p><img src="/blogs/assignment_two_files/figure-html/tfl_plot_1-1.png" width="648" style="display: block; margin: auto;" /></p>
<p>We are creating the second plot:</p>
<pre class="r"><code>df4 &lt;-bike %&gt;%
  group_by(year,week) %&gt;% #grouping by month
  filter(year&gt;2015,week!=53) %&gt;% #filtering for the year we are interested in and setting the number of weeks
  summarize(weekly_average=mean(bikes_hired)) #creating the average mean of bikes hired by every week of each year

df5 &lt;-df4 %&gt;%
  group_by(week) %&gt;% #grouping by week
  filter(year&gt;2015,week!=53) %&gt;% #filtering for the year we are interested in and setting the number of weeks
  summarize(weekly_average_overall=mean(weekly_average)) #creating the average mean of bikes hired every week no matter the year

df6 &lt;- left_join(df4, df5, by = c(&quot;week&quot;))%&gt;% 
  mutate(week_diff = ((weekly_average-weekly_average_overall)/weekly_average_overall))%&gt;% #creating the difference of expected bike rentals vs actual bikes rental
  select(year, week, week_diff) %&gt;% #selecting for the columns that we will use
  mutate(positive=if_else(0&lt;week_diff,week_diff,0), #creating a function to calculate the bike rentals deficit
         negative=if_else(0&gt;week_diff,week_diff,0),colorID=if_else(0&lt;week_diff,&quot;#7DCD85&quot;,&quot;#CB454A&quot;))  #creating a function to calculate the bike rentals excess

ggplot(df6,aes(x=week,y=week_diff,ymin=-0.6,ymax=1))+
  geom_line(group = 1) + #plotting the bike rentals
  geom_rug(data = df6, aes(color=colorID, alpha=0.4), sides = &quot;b&quot;) + 
  geom_ribbon(aes(ymin=0, ymax=negative), fill=&quot;#CB454A&quot;, alpha= 0.4)+ #colouring the deficit of bikes rentals in red
  geom_ribbon(aes(ymin=positive, ymax=0), fill=&quot;#7DCD85&quot;, alpha= 0.4)+ #colouring the excess of bikes rentals in green
  facet_wrap(~year)+ #faceting by year
  scale_y_continuous(labels=scales::percent)+ #scaling by percent for increased readibility
  scale_color_manual(values=c(&quot;#7DCD85&quot;,&quot;#CB454A&quot;))+
  theme_bw()+
  geom_rect(aes(xmin=13,xmax=26,ymin=-0.80,ymax=1.20), alpha=0.01, fill=&quot;gray&quot;)+ #colouring Q2 in gray
  geom_rect(aes(xmin=39,xmax=52,ymin=-0.80,ymax=1.20), alpha=0.01, fill=&quot;gray&quot;)+ #colouring G4 in gray
  labs(title=&quot;Weekly changes in Tfl bike rentals&quot;,
       subtitle = &quot;Change from weekly average
calculated between 2016-2019&quot;,
         y=&quot;&quot;,x=&quot;week&quot;,caption=&quot;Source: Tfl, London Data Store&quot;)+
  theme(legend.position = &quot;none&quot;, #setting a theme for increased readibility
        legend.background=element_blank(),
        plot.title=element_text(size=6,face=&quot;bold&quot;),
        axis.ticks=element_blank(),
        axis.text=element_text(size=4),
        strip.text=element_text(size=4),
        axis.title=element_text(size=4,face=&quot;bold&quot;),
        plot.subtitle=element_text(size=4),
        plot.caption = element_text(size=4),
        panel.border = element_rect(colour=&quot;white&quot;),
        strip.background = element_rect(color=&quot;transparent&quot;,fill=&quot;transparent&quot;))</code></pre>
<p><img src="/blogs/assignment_two_files/figure-html/tfl_plot_2-1.png" width="648" style="display: block; margin: auto;" /></p>
<p><strong>Should you use the mean or the median to calculate your expected rentals? Why?</strong></p>
<p>We use mean because we are looking at normal distributions. The mean is often heavily influenced by outliers, however, our data does not contain outliers. The median is usually used for skewed distributions or data with many outliers. The expected outcome value is often referred to as the “long-term” average or mean. Over the long term of doing sampling over and over, you would expect this average.</p>
</div>
</div>
<div id="challenge-2-how-has-the-cpi-and-its-components-changed-over-the-last-few-years" class="section level1">
<h1>Challenge 2: How has the CPI and its components changed over the last few years?</h1>
<div id="cleaningmodifying-data-and-building-chart" class="section level2">
<h2>Cleaning/modifying data and building chart</h2>
<p>we had some issues pulling data directly from the FED so we downloaded an excel file instead.</p>
<pre class="r"><code>#using dataset given in github under &quot;data&quot; file holder
cpi&lt;-read_csv((here::here(&quot;data&quot;, &quot;cpi_data.csv&quot;)))

#cleaning up the data and choosing the correct component title&#39;s to display
start &lt;- &quot;Consumer Price Index for All Urban Consumers: &quot;
end &lt;- &quot; in U.S. City Average&quot;

new_title&lt;-cpi$title

for(i in 1:18782){
  cpi[i,4] &lt;- strsplit(strsplit(new_title[i], start)[[1]][2], end)[[1]][1]
}

cpi_new&lt;-cpi%&gt;%
  mutate(date=ymd(date),
         year=year(date),
         year_change = value/lag(value, 12) - 1,)%&gt;% #calculating the YoY change
  select(component,date,year,value,title,year_change) %&gt;% #selecting the columns we will analyse
  filter(year&gt;2015) #filtering for the years after 2015
  
cpi_new_2&lt;-cpi_new%&gt;%
  mutate(positive=ifelse(year_change&gt; 0, 1, -1)) #creating a column to differentiate positive YoY changes vs negative YoY changes

cpi_new_3&lt;-cpi_new%&gt;%
  select(year_change,title) %&gt;% #selecting the columns we will analyse
  group_by(title)%&gt;% #grouping by titles
  filter(title!=&quot;All Items&quot;) %&gt;% #putting &quot;All Items&quot; first
  arrange(desc(year_change))%&gt;% #arrange by descening order of YoY change
  select(title)%&gt;%
  distinct()
 
component_order&lt;-c(&quot;All Items&quot;,as.character(cpi_new_3$title))

ggplot(cpi_new_2,aes(x=date,y=year_change,color=as.factor(positive)))+
   geom_point(size=0.2)+ #plotting the YoY changes
   scale_color_manual(values=c(&#39;blue2&#39;,&#39;red&#39;))+ #colouring positive YoY changes in blue and negative YoY changes in red
   geom_smooth(size=0.2,colour=&quot;grey&quot;,se=FALSE)+
   theme_bw()+ #setting a theme for increases readibility
   theme(legend.position = &quot;none&quot;,
        legend.background=element_blank(),
        plot.title=element_text(size=6,face=&quot;bold&quot;),
        axis.ticks=element_blank(),
        axis.text=element_text(size=4),
        strip.text=element_text(size=4),
        axis.title=element_text(size=4,face=&quot;bold&quot;),
        plot.subtitle=element_text(size=4),
        plot.caption = element_text(size=4),
        plot.background = element_blank(),
        panel.border = element_rect(colour=&quot;black&quot;))+
   labs(title=&quot;Yearly change of US CPI (All Items) and its components&quot;,
        subtitle= &quot;&lt;span style = &#39;font-size:12pt&#39;&gt;YoY change being &lt;span style = &#39;color: orangered;&#39;&gt;positive&lt;/span&gt; and &lt;span style = &#39;color:       steelblue1;&#39;&gt;negative&lt;/span&gt;&lt;br&gt;Jan 2016 to Aug 2021&quot;,
         y=&quot;Yoy % Change&quot;,x=&quot;&quot;,
        caption=&quot;Data from St. Louis Fed FRED
        https://fredaccount.stlouisfed/org/public/datalist/843&quot;)+
   scale_y_continuous(labels = scales::percent)+ #setting a scale in percent for increased readibility
   facet_wrap(~fct_relevel(title,component_order),scales=&quot;free&quot;) #faceting by CPI componenent and setting the scale free to maximize the area on which the YoY changes are displayed</code></pre>
<p><img src="/blogs/assignment_two_files/figure-html/cpi_plot-1.png" width="648" style="display: block; margin: auto;" /></p>
<p>Creating a new plot with the 7 key components:</p>
<pre class="r"><code>ggplot(subset(cpi_new_2,title %in% c(&quot;Housing&quot;,&quot;Transportation&quot;, &quot;Food and Beverages&quot;,&quot;Medical Care&quot;, &quot;Education and Communication&quot;, &quot;Recreation&quot;, &quot;Apparel&quot;)),aes(x=date,y=year_change,color=as.factor(positive)))+
   geom_point(size=0.2)+
  scale_color_manual(values=c(&#39;blue2&#39;,&#39;red&#39;))+
   geom_smooth(size=0.2,colour=&quot;grey&quot;,se=FALSE)+
   theme_bw()+
   theme(legend.position = &quot;none&quot;,
        legend.background=element_blank(),
        plot.title=element_text(size=6,face=&quot;bold&quot;),
        axis.ticks=element_blank(),
        axis.text=element_text(size=4),
        strip.text=element_text(size=4),
        axis.title=element_text(size=4,face=&quot;bold&quot;),
        plot.subtitle=element_text(size=4),
        plot.caption = element_text(size=4),
        plot.background = element_blank(),
        panel.border = element_rect(colour=&quot;black&quot;))+
   labs(title=&quot;Yearly change of US CPI 7 key components&quot;,
        subtitle = &quot;&lt;span style = &#39;font-size:12pt&#39;&gt;YoY change being &lt;span style = &#39;color: orangered;&#39;&gt;positive&lt;/span&gt; and &lt;span style = &#39;color:       steelblue1;&#39;&gt;negative&lt;/span&gt;&lt;br&gt;Jan 2016 to Aug 2021&quot;,
         y=&quot;Yoy % Change&quot;,x=&quot;&quot;,
        caption=&quot;Data from St. Louis Fed FRED
        https://fredaccount.stlouisfed/org/public/datalist/843&quot;)+
   scale_y_continuous(labels = scales::percent)+
  facet_wrap(~title,scales=&quot;free&quot;)</code></pre>
<p><img src="/blogs/assignment_two_files/figure-html/cpi_plot_7_key_components-1.png" width="648" style="display: block; margin: auto;" /></p>
</div>
</div>
